# Generated by Django 5.0.6 on 2024-05-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pastor_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='major_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
