# Generated by Django 5.0.6 on 2024-05-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cause_created_at_churchstate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
