# Generated by Django 5.0.6 on 2024-05-20 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pastor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pastor'),
        ),
    ]
